### ISSUE TITLE
New documentation site

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/docs#3]
I tried to use MkDocs to build a new documentation website and it seemed to work well. (I use MkDocs because it is concise, efficient and easy to use.) In addition, I set up a CI to build and publish the docs automatically. Currently the documentation remains to be improved.

Repository: https://github.com/hmsjy2017/raspbian-addons-docs-test
Preview: https://blog.iamsjy.com/raspbian-addons-docs-test

**Comment by ryanfortner** [comment]
Nice! How do you add different sections?

**Comment by hmsjy2017** [comment]
@ryanfortner refer to:
https://docs.fosshost.org 
https://github.com/fosshostorg/public-docs/tree/main/docs

**Comment by ryanfortner** [comment]
I'll open a PR on your repository in a little bit with some changes, once it's ready we can merge it into this repository.

**Comment by ryanfortner** [comment]
The new site is now live! Thanks @hmsjy2017 !
